spring:
  application:
    name: project-os-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/storage
    username: user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8080